const products = [
  {
    id: 1,
    name: "Men's Cotton Shirt",
    brand: "Levi`s",
    category: 'Shirt',
    subcategory: 'Men',
    price: 29000.99,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?...',
    detail: 'Lightweight cotton shirt perfect for everyday wear with a breathable fabric.',
    color: "white",
    userReviews: [
  ],
  discount:0
  },
  {
    id: 2,
    name: "Women's Skinny Jeans",
    brand: 'H&M',
    category: 'Jeans',
    subcategory: 'Women',
    price: 49.99,
    size: ['XS', 'S', 'M', 'L'],
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?...',
    detail: 'Stylish and snug skinny jeans with a flattering fit and stretchable denim.',
    color: "black",
    userReviews: [
    { email: 'john.doe@example.com', star: 4 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 4 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:20
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 5,
    name: "Men's Slim Trousers",
    brand: 'Adidas',
    category: 'Trousers',
    subcategory: 'Men',
    price: 1200.0,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?...',
    detail: 'Modern slim-fit trousers ideal for office or casual settings with stretch comfort.',
    color: "blue",
    userReviews: [
    { email: 'john.doe@example.com', star: 4 },
    { email: 'sarah.smith@example.com', star: 4 },
    { email: 'mike.johnson@example.com', star: 4 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:300
  },
  {
    id: 6,
    name: "Women's Elegant Blouse",
    brand: 'Levi`s',
    category: 'Top',
    subcategory: 'Women',
    price: 3100.99,
    size: ['XS', 'S', 'M'],
    image: 'https://images.unsplash.com/photo-1551232864-3f0890e580d9?...',
    detail: 'Elegant blouse with flowy fabric and a tailored fit, perfect for both work and outings.',
    color: "green",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:500
  },
  {
    id: 7,
    name: "Men's Winter Jacket",
    brand: 'Gucci',
    category: 'Jacket',
    subcategory: 'Men',
    price: 2500.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?...',
    detail: 'Insulated winter jacket with water-resistant shell and thermal lining for extreme cold.',
    color: "black",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 8,
    name: "Men's Graphic T-Shirt",
    brand: 'Nike',
    category: 'T-Shirt',
    subcategory: 'Men',
    price: 19.99,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?...',
    detail: 'Soft cotton t-shirt with premium finish for ultimate comfort and bold graphic print.',
    color: "yellow",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:5
  },
    {
    id: 1,
    name: "Men's Cotton Shirt",
    brand: "Levi`s",
    category: 'Shirt',
    subcategory: 'Men',
    price: 29000.99,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?...',
    detail: 'Lightweight cotton shirt perfect for everyday wear with a breathable fabric.',
    color: "white",
    userReviews: [
  ],
  discount:0
  },
  {
    id: 2,
    name: "Women's Skinny Jeans",
    brand: 'H&M',
    category: 'Jeans',
    subcategory: 'Women',
    price: 49.99,
    size: ['XS', 'S', 'M', 'L'],
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?...',
    detail: 'Stylish and snug skinny jeans with a flattering fit and stretchable denim.',
    color: "black",
    userReviews: [
    { email: 'john.doe@example.com', star: 4 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 4 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:20
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 5,
    name: "Men's Slim Trousers",
    brand: 'Adidas',
    category: 'Trousers',
    subcategory: 'Men',
    price: 1200.0,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?...',
    detail: 'Modern slim-fit trousers ideal for office or casual settings with stretch comfort.',
    color: "blue",
    userReviews: [
    { email: 'john.doe@example.com', star: 4 },
    { email: 'sarah.smith@example.com', star: 4 },
    { email: 'mike.johnson@example.com', star: 4 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:300
  },
  {
    id: 6,
    name: "Women's Elegant Blouse",
    brand: 'Levi`s',
    category: 'Top',
    subcategory: 'Women',
    price: 3100.99,
    size: ['XS', 'S', 'M'],
    image: 'https://images.unsplash.com/photo-1551232864-3f0890e580d9?...',
    detail: 'Elegant blouse with flowy fabric and a tailored fit, perfect for both work and outings.',
    color: "green",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:500
  },
  {
    id: 7,
    name: "Men's Winter Jacket",
    brand: 'Gucci',
    category: 'Jacket',
    subcategory: 'Men',
    price: 2500.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?...',
    detail: 'Insulated winter jacket with water-resistant shell and thermal lining for extreme cold.',
    color: "black",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 8,
    name: "Men's Graphic T-Shirt",
    brand: 'Nike',
    category: 'T-Shirt',
    subcategory: 'Men',
    price: 19.99,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?...',
    detail: 'Soft cotton t-shirt with premium finish for ultimate comfort and bold graphic print.',
    color: "yellow",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:5
  },
    {
    id: 1,
    name: "Men's Cotton Shirt",
    brand: "Levi`s",
    category: 'Shirt',
    subcategory: 'Men',
    price: 29000.99,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?...',
    detail: 'Lightweight cotton shirt perfect for everyday wear with a breathable fabric.',
    color: "white",
    userReviews: [
  ],
  discount:0
  },
  {
    id: 2,
    name: "Women's Skinny Jeans",
    brand: 'H&M',
    category: 'Jeans',
    subcategory: 'Women',
    price: 49.99,
    size: ['XS', 'S', 'M', 'L'],
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?...',
    detail: 'Stylish and snug skinny jeans with a flattering fit and stretchable denim.',
    color: "black",
    userReviews: [
    { email: 'john.doe@example.com', star: 4 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 4 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:20
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 5,
    name: "Men's Slim Trousers",
    brand: 'Adidas',
    category: 'Trousers',
    subcategory: 'Men',
    price: 1200.0,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?...',
    detail: 'Modern slim-fit trousers ideal for office or casual settings with stretch comfort.',
    color: "blue",
    userReviews: [
    { email: 'john.doe@example.com', star: 4 },
    { email: 'sarah.smith@example.com', star: 4 },
    { email: 'mike.johnson@example.com', star: 4 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:300
  },
  {
    id: 6,
    name: "Women's Elegant Blouse",
    brand: 'Levi`s',
    category: 'Top',
    subcategory: 'Women',
    price: 3100.99,
    size: ['XS', 'S', 'M'],
    image: 'https://images.unsplash.com/photo-1551232864-3f0890e580d9?...',
    detail: 'Elegant blouse with flowy fabric and a tailored fit, perfect for both work and outings.',
    color: "green",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:500
  },
  {
    id: 7,
    name: "Men's Winter Jacket",
    brand: 'Gucci',
    category: 'Jacket',
    subcategory: 'Men',
    price: 2500.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?...',
    detail: 'Insulated winter jacket with water-resistant shell and thermal lining for extreme cold.',
    color: "black",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 8,
    name: "Men's Graphic T-Shirt",
    brand: 'Nike',
    category: 'T-Shirt',
    subcategory: 'Men',
    price: 19.99,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?...',
    detail: 'Soft cotton t-shirt with premium finish for ultimate comfort and bold graphic print.',
    color: "yellow",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:5
  },
    {
    id: 1,
    name: "Men's Cotton Shirt",
    brand: "Levi`s",
    category: 'Shirt',
    subcategory: 'Men',
    price: 29000.99,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?...',
    detail: 'Lightweight cotton shirt perfect for everyday wear with a breathable fabric.',
    color: "white",
    userReviews: [
  ],
  discount:0
  },
  {
    id: 2,
    name: "Women's Skinny Jeans",
    brand: 'H&M',
    category: 'Jeans',
    subcategory: 'Women',
    price: 49.99,
    size: ['XS', 'S', 'M', 'L'],
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?...',
    detail: 'Stylish and snug skinny jeans with a flattering fit and stretchable denim.',
    color: "black",
    userReviews: [
    { email: 'john.doe@example.com', star: 4 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 4 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:20
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 5,
    name: "Men's Slim Trousers",
    brand: 'Adidas',
    category: 'Trousers',
    subcategory: 'Men',
    price: 1200.0,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?...',
    detail: 'Modern slim-fit trousers ideal for office or casual settings with stretch comfort.',
    color: "blue",
    userReviews: [
    { email: 'john.doe@example.com', star: 4 },
    { email: 'sarah.smith@example.com', star: 4 },
    { email: 'mike.johnson@example.com', star: 4 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:300
  },
  {
    id: 6,
    name: "Women's Elegant Blouse",
    brand: 'Levi`s',
    category: 'Top',
    subcategory: 'Women',
    price: 3100.99,
    size: ['XS', 'S', 'M'],
    image: 'https://images.unsplash.com/photo-1551232864-3f0890e580d9?...',
    detail: 'Elegant blouse with flowy fabric and a tailored fit, perfect for both work and outings.',
    color: "green",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:500
  },
  {
    id: 7,
    name: "Men's Winter Jacket",
    brand: 'Gucci',
    category: 'Jacket',
    subcategory: 'Men',
    price: 2500.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?...',
    detail: 'Insulated winter jacket with water-resistant shell and thermal lining for extreme cold.',
    color: "black",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 8,
    name: "Men's Graphic T-Shirt",
    brand: 'Nike',
    category: 'T-Shirt',
    subcategory: 'Men',
    price: 19.99,
    size: ['S', 'M', 'L', 'XL'],
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?...',
    detail: 'Soft cotton t-shirt with premium finish for ultimate comfort and bold graphic print.',
    color: "yellow",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 4 },
  ],
  discount:5
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
  {
    id: 3,
    name: 'Unisex Pocket Hoodie',
    brand: 'Nike',
    category: 'Hoodie',
    subcategory: 'Men',
    price: 3900.99,
    size: ['M', 'L', 'XL', 'XXL'],
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?...',
    detail: 'Cozy unisex hoodie made with brushed fleece and kangaroo front pocket.',
    color: "white",
    userReviews: [
    { email: 'john.doe@example.com', star: 5 },
    { email: 'sarah.smith@example.com', star: 5 },
    { email: 'mike.johnson@example.com', star: 5 },
    { email: 'jasson@gmail.com', star: 5 },
  ],
  discount:200
  },
];

/*color data here*/

const colorData = [
  "Blue","Beige", "Black","Bronze", "Brown",
  "Camel", "Charcoal", "Copper", "Coral", "Cream",
  "Denim Blue", "Dusty Rose", "Gold", "Gray", "Green",
  "Hot Pink", "Ivory", "Lavender", "Light Blue", "Light Gray",
  "Lilac", "Lime Green", "Maroon", "Mauve", "Mint",
  "Mustard", "Navy", "Off White", "Olive", "Orange",
  "Pastel Blue", "Pastel Green", "Pastel Pink", "Pastel Yellow", "Peach",
  "Pink", "Purple", "Red", "Rose Gold", "Rust",
  "Sea Green", "Silver", "Sky Blue", "Slate", "Tan",
  "Teal", "Violet", "White", "Wine"
];



  const categoryData=["Men","Women","Boys","Girls","Babies"]
const subCategoryData = [
  "Activewear", "Blouses", "Dresses", "Dungarees", "Ethnic Wear",
  "Hoodies", "Innerwear", "Jackets", "Jeans", "Kurtis",
  "Lehengas", "Overalls", "Sarees", "Shirts", "Shorts",
  "Skirts", "Sleepwear", "Suits & Sets", "Sweatshirts", "T-Shirts",
  "Tracksuits", "Trousers", "Winter Wear"
];;

export {products,colorData,categoryData,subCategoryData};
